spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/demo
    login: sa
  jpa:
    show-sql=true: true
    open-in-view=false: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  h2:
    console:
      enabled: true
      web-allow-other: true
    allowed.resources: /h2-console/**

server:
  error:
    include-message: always